name: pnp_test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - cmake=4.3.4
  - ninja=1.13.1
  - pip:
      - build==1.5.0
      - matplotlib==3.11.1
      - numpy==2.5.1
      - opencv-python-headless==5.0.0.93
      - pytest==9.1.1
